import { Beverage, Category } from "../interface/Beverage";

const OnePlusKopiMenu: Beverage[] = [
  { category: Category.TraditionalCoffee, name: "Kopi O (Hot)", price: 1.1 },
  { category: Category.TraditionalCoffee, name: "Kopi O (Iced)", price: 1.4 },
  { category: Category.TraditionalCoffee, name: "Teh O (Hot)", price: 1.1 },
  { category: Category.TraditionalCoffee, name: "Teh O (Iced)", price: 1.4 },
  { category: Category.TraditionalCoffee, name: "Kopi (Hot)", price: 1.2 },
  { category: Category.TraditionalCoffee, name: "Kopi (Iced)", price: 1.7 },
  { category: Category.TraditionalCoffee, name: "Teh (Hot)", price: 1.2 },
  { category: Category.TraditionalCoffee, name: "Teh (Iced)", price: 1.7 },
  { category: Category.TraditionalCoffee, name: "Kopi C (Hot)", price: 1.4 },
  { category: Category.TraditionalCoffee, name: "Kopi C (Iced)", price: 1.9 },
  { category: Category.TraditionalCoffee, name: "Teh C (Hot)", price: 1.4 },
  { category: Category.TraditionalCoffee, name: "Teh C (Iced)", price: 1.9 },
  { category: Category.TraditionalCoffee, name: "HK Yuan Yang (Hot)", price: 1.7 },
  { category: Category.TraditionalCoffee, name: "HK Yuan Yang (Iced)", price: 2.2 },
  { category: Category.TraditionalCoffee, name: "Milo (Hot)", price: 1.4 },
  { category: Category.TraditionalCoffee, name: "Milo (Iced)", price: 1.9 },
  { category: Category.TraditionalCoffee, name: "Milo C (Hot)", price: 1.5 },
  { category: Category.TraditionalCoffee, name: "Milo C (Iced)", price: 2.0 },
  { category: Category.TraditionalCoffee, name: "Lemon Tea (Hot)", price: 1.4 },
  { category: Category.TraditionalCoffee, name: "Lemon Tea (Iced)", price: 1.7 },
  { category: Category.TraditionalCoffee, name: "Honey Lemon (Hot)", price: 1.8 },
  { category: Category.TraditionalCoffee, name: "Honey Lemon (Iced)", price: 2.5 },
  { category: Category.TraditionalCoffee, name: "YuZu Tea (Hot)", price: 1.8 },
  { category: Category.TraditionalCoffee, name: "YuZu Tea (Iced)", price: 2.8 },
  { category: Category.TraditionalCoffee, name: "Milo Dino (Iced)", price: 3.0 },
  { category: Category.TraditionalCoffee, name: "Milo-Coffee Dino (Iced)", price: 3.0 },
  { category: Category.IceBlended, name: "Coffee / Mocha", price: 4.5 },
  { category: Category.IceBlended, name: "Cookie + Cream", price: 4.5 },
  { category: Category.IceBlended, name: "Matcha + Milk", price: 4.5 },
  { category: Category.IceBlended, name: "Mixed Berries", price: 4.5 },
  { category: Category.IceBlended, name: "Lychee", price: 4.5 },
  { category: Category.IceBlended, name: "Mango", price: 4.5 },
  { category: Category.IceBlended, name: "Passion Fruit", price: 4.5 },
  { category: Category.IceBlended, name: "Honey YuZu", price: 4.5 },
  { category: Category.HotFlowerTea, name: "Chrysanthemum Goji", price: 1.6 },
  { category: Category.HotFlowerTea, name: "Rose Goji", price: 1.6 },
  { category: Category.HotFlowerTea, name: "Honey BlackFruit Wolfberry", price: 1.6 },
  { category: Category.SpecialtyIcedDrinks, name: "Lychee Tea", price: 2.8 },
  { category: Category.SpecialtyIcedDrinks, name: "Honey Passion Fruit", price: 3.0 },
  { category: Category.SpecialtyIcedDrinks, name: "Lychee Aloe Vera", price: 3.5 },
  { category: Category.SpecialtyIcedDrinks, name: "Honey Lemon Aloe Vera", price: 3.5 }
]

export default OnePlusKopiMenu;