import { Beverage, Category } from "../interface/Beverage";

const OnePlusKopiMenu: Beverage[] = [
  { id: 101 ,category: Category.TraditionalCoffee, name: "Kopi O (Hot)", price: 1.1 },
  { id: 102 ,category: Category.TraditionalCoffee, name: "Kopi O (Iced)", price: 1.4 },
  { id: 103 ,category: Category.TraditionalCoffee, name: "Teh O (Hot)", price: 1.1 },
  { id: 104 ,category: Category.TraditionalCoffee, name: "Teh O (Iced)", price: 1.4 },
  { id: 105 ,category: Category.TraditionalCoffee, name: "Kopi (Hot)", price: 1.2 },
  { id: 106 ,category: Category.TraditionalCoffee, name: "Kopi (Iced)", price: 1.7 },
  { id: 107 ,category: Category.TraditionalCoffee, name: "Teh (Hot)", price: 1.2 },
  { id: 108 ,category: Category.TraditionalCoffee, name: "Teh (Iced)", price: 1.7 },
  { id: 109 ,category: Category.TraditionalCoffee, name: "Kopi C (Hot)", price: 1.4 },
  { id: 110 ,category: Category.TraditionalCoffee, name: "Kopi C (Iced)", price: 1.9 },
  { id: 111 ,category: Category.TraditionalCoffee, name: "Teh C (Hot)", price: 1.4 },
  { id: 112 ,category: Category.TraditionalCoffee, name: "Teh C (Iced)", price: 1.9 },
  { id: 113 ,category: Category.TraditionalCoffee, name: "HK Yuan Yang (Hot)", price: 1.7 },
  { id: 114 ,category: Category.TraditionalCoffee, name: "HK Yuan Yang (Iced)", price: 2.2 },
  { id: 115 ,category: Category.TraditionalCoffee, name: "Milo (Hot)", price: 1.4 },
  { id: 116 ,category: Category.TraditionalCoffee, name: "Milo (Iced)", price: 1.9 },
  { id: 117 ,category: Category.TraditionalCoffee, name: "Milo C (Hot)", price: 1.5 },
  { id: 118 ,category: Category.TraditionalCoffee, name: "Milo C (Iced)", price: 2.0 },
  { id: 119 ,category: Category.TraditionalCoffee, name: "Lemon Tea (Hot)", price: 1.4 },
  { id: 120 ,category: Category.TraditionalCoffee, name: "Lemon Tea (Iced)", price: 1.7 },
  { id: 121 ,category: Category.TraditionalCoffee, name: "Honey Lemon (Hot)", price: 1.8 },
  { id: 122 ,category: Category.TraditionalCoffee, name: "Honey Lemon (Iced)", price: 2.5 },
  { id: 123 ,category: Category.TraditionalCoffee, name: "YuZu Tea (Hot)", price: 1.8 },
  { id: 124 ,category: Category.TraditionalCoffee, name: "YuZu Tea (Iced)", price: 2.8 },
  { id: 125 ,category: Category.TraditionalCoffee, name: "Milo Dino (Iced)", price: 3.0 },
  { id: 126 ,category: Category.TraditionalCoffee, name: "Milo-Coffee Dino (Iced)", price: 3.0 },
  { id: 201 ,category: Category.IceBlended, name: "Coffee / Mocha", price: 4.5 },
  { id: 202 ,category: Category.IceBlended, name: "Cookie + Cream", price: 4.5 },
  { id: 203 ,category: Category.IceBlended, name: "Matcha + Milk", price: 4.5 },
  { id: 204 ,category: Category.IceBlended, name: "Mixed Berries", price: 4.5 },
  { id: 205 ,category: Category.IceBlended, name: "Lychee", price: 4.5 },
  { id: 206 ,category: Category.IceBlended, name: "Mango", price: 4.5 },
  { id: 207 ,category: Category.IceBlended, name: "Passion Fruit", price: 4.5 },
  { id: 208 ,category: Category.IceBlended, name: "Honey YuZu", price: 4.5 },
  { id: 301 ,category: Category.HotFlowerTea, name: "Chrysanthemum Goji", price: 1.6 },
  { id: 302 ,category: Category.HotFlowerTea, name: "Rose Goji", price: 1.6 },
  { id: 303 ,category: Category.HotFlowerTea, name: "Honey BlackFruit Wolfberry", price: 1.6 },
  { id: 401 ,category: Category.SpecialtyIcedDrinks, name: "Lychee Tea", price: 2.8 },
  { id: 402 ,category: Category.SpecialtyIcedDrinks, name: "Honey Passion Fruit", price: 3.0 },
  { id: 403 ,category: Category.SpecialtyIcedDrinks, name: "Lychee Aloe Vera", price: 3.5 },
  { id: 404 ,category: Category.SpecialtyIcedDrinks, name: "Honey Lemon Aloe Vera", price: 3.5 }
]

export default OnePlusKopiMenu;